stan-dev/cmdstanr

tests/testthat/answers/model-code-output, tests/testthat/answers/model-print-output, tests/testthat/resources/stan/bernoulli.stan
Fixes #35 
This PR changes the example model for the test resources & answers. For reasons behind this change see the issue.
=> Change the test example model

.appveyor.yml, R/model.R, R/run.R, tests/testthat/helper-envvars-and-paths.R, tests/testthat/test-failed-chains.R, tests/testthat/test-fit.R, tests/testthat/test-model-compile.R, tests/testthat/test-model-init.R, tests/testthat/test-model-optimize.R, tests/testthat/test-model-sample-metric.R, tests/testthat/test-model-sample.R, tests/testthat/test-model-variational.R, tests/testthat/test-path.R
Fixes #80 by adding support for testing on appveyor.
For now this builds the package and runs:
R CMD check with the flags: "--no-manual --as-cran --install-args=--build"
Rok Češnovar, University of Ljubljana
=> Add Appveyor Windows testing

.travis.yml, R/utils.R, tests/testthat/test-model-compile.R
Fixes #86 
The problem turned out to be that `make/local` didn't exist and we didn't have sufficient permissions in that travis directory in order to create it via `writeLines()` in `set_make_local()`. So I ended up creating `make/local` and changing the permissions in `before_install` in `.travis.yml`: 
```
before_install:
- sudo bash inst/make_cmdstan.sh -j2 -o
- sudo touch $HOME/.cmdstanr/cmdstan/make/local
- sudo chown -R $USER:$USER $HOME/.cmdstanr/cmdstan/make/local
```
I'm not sure if this is the best way of resolving this but it seems to work. @rok-cesnovar If you have a better idea I'm happy to go with a different solution. 
**Columbia …
=> Fix travis recompilation test

.travis.yml, R/run.R
Fixes #92 and might also squash #69 for good now.
Adds printing of stderr to the background process handling.
Thanks @bbbales2 for finding this one.
=> Process stderr

R/run.R
Small typo in line 309 run.R fixed p$kill_tree() -> p$kill_tree
Reference to issue #97 
Please describe the purpose of the pull request. 
Carlos, Traynor Univ. of Warwick
=> Fix to bug 97

vignettes/cmdstanr.Rmd
There's no mention of `cmdstan_version()` in the vignette, so it's hard to discover (see #107).
Marco Colombo
=> Mention cmdstan_version() in the vignette

.appveyor.yml, R/model.R, man/model-method-sample.Rd, tests/testthat/test-path.R, tests/testthat/test-utils.R
A few minor stuff:
- Adds a few edge case tests to improve coverage. 
- Adds xml2 to the list of packages to install on appveyor because I saw it fail once with "Error: Please install xml2 package"
- fixes the typo mentioned in #87 
=> Improve code coverage

R/args.R, R/path.R, tests/testthat/test-fit-mle.R, tests/testthat/test-fit-vb.R, tests/testthat/test-install.R, tests/testthat/test-model-output_dir.R
Should fix issue #112 and also comments out the currently failing tests that are failing due to changes in the posterior package.
Rok Češnovar
=> Fix for R version < 3.5.0

R/fit.R, man/CmdStanMCMC.Rd, tests/testthat/test-fit-mcmc.R
Fixes #123 by adding 
```R
fit$draws(inc_warmup=FALSE) 
fit$draws(inc_warmup=TRUE) 
fit$sampler_diagnostics(inc_warmup=FALSE) 
fit$sampler_diagnostics(inc_warmup=TRUE) 
```
Rok Češnovar
=> Refactor method for accessing draws and diagnostics

R/fit.R, R/model.R, R/read_csv.R, R/utils.R, docs/reference/CmdStanMLE.html, docs/reference/CmdStanModel.html, docs/reference/cmdstan_model.html, docs/reference/cmdstanr-package.html, docs/reference/fit-method-draws.html, docs/reference/model-method-optimize.html, docs/reference/model-method-sample.html, docs/reference/model-method-variational.html, man/CmdStanMLE.Rd, man/CmdStanModel.Rd, man/cmdstan_model.Rd, man/cmdstanr-package.Rd, man/fit-method-draws.Rd, man/model-method-optimize.Rd, man/model-method-sample.Rd, man/model-method-variational.Rd, tests/testthat/test-fit-mle.R, tests/testthat/test-fit-vb.R
Closes #21 
A bit of minor refactoring that improves consistency of fitted model objects (and slightly simplifies them). Also a bunch of doc updates so that's why so many files are changed. 
=> Improve fitted objects consistency

.appveyor.yml, R/run.R, docs/articles/cmdstanr.html, docs/reference/CmdStanModel.html, docs/reference/cmdstan_model.html, docs/reference/cmdstanr-package.html, docs/reference/model-method-optimize.html, docs/reference/model-method-sample.html, docs/reference/model-method-variational.html, tests/testthat/resources/stan/init_warnings.stan, tests/testthat/test-failed-chains.R, tests/testthat/test-model-sample.R
=> Initialization failure warnings fix

R/args.R, tests/testthat/test-fit-mcmc.R, tests/testthat/test-fit-vb.R, tests/testthat/test-model-optimize.R
Fixes #177 
Rok Češnovar, University of Ljubljana
=> Prevent scientific format on cmdstan args

R/read_csv.R, tests/testthat/test-csv.R
=> return correct step size

R/fit.R, R/model.R, docs/reference/fit-method-summary.html, docs/reference/model-method-sample.html, man/fit-method-summary.Rd, man/model-method-sample.Rd
closes #181
As reasonably requested by @bbbales2: 
* Clarifies that `save_warmup=TRUE` doesn't automatically include warmup draws unless using `$draws(inc_warmup=TRUE)`. 
* Clarifies that `$summary()` doesn't include warmup draws. 
=> more doc clarifications about warmup draws

DESCRIPTION, R/run.R, tests/testthat/test-threads.R
Fix threading, STAN_NUM_THREADS was not set after refactor.
=> Bugfix threading

.github/workflows/R-CMD-check.yaml, R/model.R, tests/testthat/resources/stan/fail.stan, tests/testthat/test-model-compile.R
=> Nicer compile error messages

R/run.R
=> Suppress cmdstan commands

R/fit.R, tests/testthat/resources/stan/.gitignore, tests/testthat/test-example.R, tests/testthat/test-failed-chains.R, tests/testthat/test-fit-mcmc.R, tests/testthat/test-fit-mle.R, tests/testthat/test-fit-shared.R, tests/testthat/test-fit-vb.R, tests/testthat/test-path.R
Just cleans up some code and adds some tests. Also added compiled files that are produced during tests to .gitignore. I run separate tests often so I have to be careful not committing those files in.
=> Some code cleanup and test coverage improvement

R/fit.R, R/model.R, docs/reference/model-method-sample.html, man/model-method-sample.Rd
* Add a bit more to `fixed_param` doc
* Set `private$metadata_` during `initialize()` so it is never accessed before it is created. Avoids `Error in !private$metadata_$save_warmup : invalid argument type` when trying `draws(inc_warmup=TRUE)` after `fixed_param`. Correct error (now thrown) is about no warmup draws. 
=> Minor `fixed_param` edits

R/install.R
=> Use precompiled headers on windows with rtools 4.0

R/knitr.R, man/eng_cmdstan.Rd, man/register_knitr_engine.Rd, vignettes/r-markdown.Rmd
To address [Failure compiling Stan model chunk in .Rmd](https://discourse.mc-stan.org/t/failure-compiling-stan-model-chunk-in-rmd/17280), which results when running chunks interactively (including but not limited to R Notebooks).
**Mikhail Popov**
=> Notes on running rmd chunks interactively

R/data.R, tests/testthat/test-data.R, tests/testthat/test-model-data.R
fixes #283
Throws an error if any NA elements in the list of data
=> error if NAs in data list

R/run.R, tests/testthat/test-fit-mle.R, tests/testthat/test-fit-shared.R, tests/testthat/test-model-sample.R
=> Fix optimization, transformed data prints

NEWS.md, R/model.R, tests/testthat/test-model-compile.R
=> Fix stanc options handling in check_syntax

NEWS.md, R/read_csv.R
=> Add drop = FALSE when slicing draws

R/fit.R, R/read_csv.R, R/utils.R, tests/testthat/test-utils.R
`matching_variables()` was super slow with larger number of parameters. This PR speeds it up a bit.
=> Speedup matching variable names

.github/workflows/R-CMD-check.yaml, .github/workflows/Test-coverage.yaml
=> replace add-path in Github Actions

R/utils.R, tests/testthat/test-model-compile.R, tests/testthat/test-utils.R
Fixes an issue with cpp_options when 2 or more of them are used together.
Rok Češnovar
=> cpp_options fix

R/model.R, tests/testthat/test-model-compile.R
=> Fix double pedantic warning prints

R/read_csv.R, tests/testthat/test-data.R
=> Bugfix 364

R/install.R, R/utils.R
install_cmdstan now compiles an arm64e cmdstan on Apple Silicon
Nico Kist
=> install_cmdstan now compiles an arm64e cmdstan on Apple Silicon

.github/workflows/R-CMD-check.yaml, .github/workflows/Test-coverage.yaml, NEWS.md
=> Use Github version of processx on CI

R/fit.R, docs/reference/fit-method-summary.html, man/fit-method-summary.Rd
Updates doc to explain the speed difference between the print and summary methods. This was brought up in #377.
=> clarify print vs summary in doc

R/path.R
Fixes #378 
Columbia University (Jonah's code)
Rok Češnovar (made a branch)
=> Error if CMDSTAN_VERSION is not present

.github/workflows/R-CMD-check.yaml, .github/workflows/Test-coverage.yaml, DESCRIPTION
=> Set min processx version

tests/testthat/test-knitr.R
Adds some tests for `eng_cmdstan()` and `register_knitr_engine()`. 
=> Add a few tests for eng_cmdstan and register_knitr_engine

README.md, docs/articles/cmdstanr.html, docs/index.html, vignettes/cmdstanr.Rmd
Recommend in installation instructions to restart R before installing the cmdstanr R packages. 
Totally unrelated: I also changed a few section headers in the vignette to make the table of contents more useful. 
=> recommend new R session when installing

docs/articles/cmdstanr.html, vignettes/cmdstanr.Rmd
Fixes broken url in vignette. 
=> fix url in vignette

.github/workflows/Test-coverage.yaml, R/fit.R, R/knitr.R, R/run.R, R/utils.R, tests/testthat/test-knitr.R
Some super minor cleaning of `utils.R`: 
* `suggest_package()` helper function
* organize OS and hardware related checks
* cleanup some unnecessary doc (we don't need 3 lines of doc for 1 line functions that are easy to understand like `os_is_windows()`)
* `check_target_exe()` is only used once in run.R so just move it there
**Columbia university**
=> Utils cleanup

R/install.R, tests/testthat/test-example.R, tests/testthat/test-fit-mle.R, tests/testthat/test-fit-shared.R, tests/testthat/test-install.R, tests/testthat/test-model-generate_quantities.R, tests/testthat/test-model-optimize.R, tests/testthat/test-model-variational.R
Needed a mindless break from some other work so I added a few more tests for cases that were missing. 
=> Improve test coverage

R/cmdstanr-package.R, R/data.R, R/example.R, R/model.R, R/utils.R, _pkgdown.yml, man/CmdStanModel.Rd, man/cmdstan_model.Rd, man/cmdstanr-package.Rd, man/cmdstanr_example.Rd, man/model-method-check_syntax.Rd, man/model-method-compile.Rd, man/model-method-generate-quantities.Rd, man/model-method-optimize.Rd, man/model-method-sample.Rd, man/model-method-sample_mpi.Rd, man/model-method-variational.Rd, tests/testthat/helper-envvars-and-paths.R, vignettes/children/comparison-with-rstan.md, vignettes/children/settings-knitr.Rmd, vignettes/cmdstanr-internals.Rmd, vignettes/cmdstanr.Rmd, vignettes/r-markdown.Rmd
I needed some more mindless distraction so I did some more minor cleaning up ;)
=> More cleanup

.github/workflows/R-CMD-check.yaml, R/run.R, tests/testthat/test-failed-chains.R, tests/testthat/test-fit-shared.R, tests/testthat/test-model-compile.R
Cmdstan 2.26 has some minor changes in the output that we use in tests. This fixes those issues.
Rok Češnovar
=> Fixes for test for cmdstan 2.26

.github/workflows/R-CMD-check.yaml, .github/workflows/Test-coverage.yaml, tests/testthat/test-install.R
=> Remove -rc1 from CI tests

R/model.R
=> cleanup the use of model_name

tests/testthat/helper-models.R, tests/testthat/test-failed-chains.R, tests/testthat/test-fit-mle.R, tests/testthat/test-fit-shared.R, tests/testthat/test-model-init.R, tests/testthat/test-model-optimize.R, tests/testthat/test-model-sample-metric.R, tests/testthat/test-model-variational.R, tests/testthat/test-profiling.R
This just adds seed to various testing runs, occasionally some optimization/VI runs fail on random. Adding a seed might help track those down. It certainly wont hurt. Will merge if tests pass.
Rok Češnovar
=> Specify seed in tests

DESCRIPTION, NEWS.md, R/args.R, R/data.R, R/example.R, R/fit.R, R/install.R, R/path.R, man/cmdstanr-package.Rd, man/cmdstanr_example.Rd, man/fit-method-loo.Rd, man/install_cmdstan.Rd, man/set_cmdstan_path.Rd, vignettes/children/comparison-with-rstan.md
A bunch of small doc edits. Also bumped the version to 0.4.09000. 
=> Minor doc edits

R/csv.R
Just fixing a minor typo in the examples section of `as_cmdstan_fit()`
Mike Lawrence
=> replace as_cmdstan_mcmc with as_cmdstan_fit in csv.R examples section

R/model.R
Fixes https://github.com/stan-dev/cmdstanr/issues/29#issuecomment-831651530
=> check if stan_opencl is TRUE rather than just not NULL

R/args.R, R/csv.R, R/data.R, R/example.R, R/fit.R, R/install.R, R/knitr.R, R/model.R, R/path.R, R/run.R, R/utils.R, R/zzz.R, man/cmdstan_default_path.Rd, man/install_cmdstan.Rd, man/set_cmdstan_path.Rd, tests/testthat/test-csv.R, tests/testthat/test-model-compile.R, tests/testthat/test-model-init.R, tests/testthat/test-utils.R
Just a minor procrastination PR with a little bit of cleanup/linting. Will merge if CI passes since there are no real changes here.  
=> Minor cleanup

R/fit.R, tests/testthat/test-fit-shared.R, tests/testthat/test-profiling.R
Fixes #507 
@wlandau would you mind checking that this plays nice with stantargets. I am 95% sure it should but just in case. Also no rush, whenever you have time.
Rok Češnovar
=> Store profiling in fit after reading it in once

R/model.R
=> Catch C++ compiler error for full disk

.github/pull_request_template.md, README.md
Adds license information for documentation to the readme and the PR template. 
=> add info about license for doc

.github/workflows/R-CMD-check.yaml, .github/workflows/Test-coverage.yaml, tests/testthat/test-failed-chains.R, tests/testthat/test-model-compile.R
A few changes in the unit tests due to changes in the error messages and that they are printed correctly stderr now.
Rok Češnovar
=> Fixes for unit tests after 2.27.0 release

R/data.R, tests/testthat/test-csv.R, tests/testthat/test-json.R
closes #515
Error if duplicate names in data
=> error if duplicate names in data

R/csv.R, tests/testthat/test-csv.R
fixes #525
Fixes #525 by checking if `length(draws) == 0` before trying to index it. 
=> Fix read_cmdstan_csv with no variables after variational/optimize

.github/workflows/R-CMD-check.yaml, .github/workflows/Test-coverage.yaml, .github/workflows/cmdstan-tarball-check.yaml, DESCRIPTION
We can now switch to posterior from CRAN.
Rok Češnovar
=> Use `posterior` from CRAN

DESCRIPTION
=> Bump posterior to 1.1.0

NEWS.md, R/model.R, tests/testthat/test-model-sample.R
=> Set fixed_param = TRUE when the model has no parameters

R/install.R
=> On install, report if the previous installation had a non-empty make/local file

R/model.R, tests/testthat/test-model-compile.R, tests/testthat/test-model-optimize.R, tests/testthat/test-model-sample.R, tests/testthat/test-model-variables.R, tests/testthat/test-model-variational.R
=> Handle the case where Stan file is removed after compilation

.github/workflows/R-CMD-check.yaml, .github/workflows/cmdstan-tarball-check.yaml
=> GHA: Linux: Update system dependencies

R/model.R, tests/testthat/test-threads.R
=> Fix issue with `stan_threads=FALSE` or `stan_threads=something`

R/data.R
This is a much faster way of writing out a CSV file (a factor of 2-3) and it can be very beneficial with large numbers of parameters.
Rok Češnovar
=> Use data.table::fwrite to write draws to CSV

DESCRIPTION
See title. We fixed quite a few bugs in the process of 0.4.0.9000. Lets just bump to 9001 for now so users can easily differentiate.
Rok Češnovar
=> Bump version number to 0.4.0.9001

R/model.R, tests/testthat/test-model-compile.R
=> Dont capitalize cpp_options elements with no names

R/csv.R, tests/testthat/test-fit-mcmc.R
Fixes #621 
This is a simple as it goes, will merge if tests pass.
Rok Češnovar
=> Fix metadata()$time for chains > 1

R/model.R, tests/testthat/test-model-compile.R
=> Include current folder in include_paths if NULL

dependabot.yml
Adds the Github Dependabot to check for automatic updates to the Github Actions scripts so we don't have to keep updating it manually.
Rok Češnovar
=> Adds dependabot

R/install.R, R/model.R
=> A better warning message in case of running R inside a Rosetta2 app

R/model.R, R/utils.R, tests/testthat/test-model-compile.R
=> add stancflags from make/local

R/model.R, man/model-method-format.Rd
=> fix error in example usage of model$format

R/fit.R, man/fit-method-summary.Rd, vignettes/cmdstanr.Rmd
Fixes #617 
Add examples for summary function.
F. Hoffman-La Roche
=> more examples

DESCRIPTION
closes #752
I didn't run the unit tests locally, will let GHA do it for this tiny PR 
Bump posterior version to avoid weird print output 
=> bump posterior version

docs/articles/cmdstanr-internals.html, vignettes/cmdstanr-internals.Rmd
Remove section on saving objects in internals vignette now that there's a section in main vignette
=> Remove section on saving objects in internals vignette now that there's a section in main vignette

vignettes/articles-online-only/opencl.Rmd
Minor update to array syntax in website OpenCL vignette
Andrew Johnson
=> Update array syntax in website vignette

R/model.R, man/CmdStanModel.Rd, man/cmdstan_model.Rd, man/cmdstanr-package.Rd, man/model-method-laplace.Rd, man/model-method-optimize.Rd, man/model-method-pathfinder.Rd, man/model-method-sample.Rd, man/model-method-variational.Rd
=> Improve Pathfinder doc

DESCRIPTION
- [x Run unit tests
Bumping DESCRIPTION for release
Andrew Johnson
=> Prepare v0.7.1 bugfix-release

R/model.R, R/utils.R, tests/testthat/test-install.R, tests/testthat/test-model-compile.R, tests/testthat/test-model-laplace.R, tests/testthat/test-model-optimize.R
Fix test failures under cmdstan 2.34
Andrew Johnson
=> Fix test failures under cmdstan 2.34

vignettes/articles-online-only/opencl.Rmd
Current link is broken. I've changed it to what appears to be the current correct link, but I'm not positive.
- [ x] Declare copyright holder and agree to license (see below)
Purpose: Fix broken link in OpenCL Vignette.
Joel Schwartz
=> Update broken link in opencl.Rmd

.github/workflows/R-CMD-check-wsl.yaml, .github/workflows/R-CMD-check.yaml, .github/workflows/Test-coverage.yaml, .github/workflows/cmdstan-tarball-check.yaml, R/install.R
Fix compatibility with new RTools & R versions
Andrew Johnson
=> Add handling for new rtools version

R/install.R
Just picked changes from #958 
Andrew Johnson
=> Fix rtools44 version alignment

.github/workflows/R-CMD-check-wsl.yaml, .github/workflows/R-CMD-check.yaml, .github/workflows/Test-coverage.yaml, R/install.R, tests/testthat/test-install.R
Github has changed the MacOS runners to arm64, causing issues with the current cache.
Andrew Johnson
=> Fix Github Workflows 

.github/workflows/R-CMD-check.yaml
`stringi` is currently [broken on Windows r-devel](https://github.com/gagolews/stringi/issues/508), so disable the workflow for now
Andrew Johnson
=> Temporarily disable win r-devel check due to stringi breakage

.Rbuildignore, DESCRIPTION, NEWS.md, R/model.R, R/path.R, README.md, man/CmdStanModel.Rd
Update metadata and NEWS for release
Andrew Johnson
=> Prepare v0.8.0 release

R/model.R, R/run.R, man/model-method-laplace.Rd, man/model-method-optimize.Rd, man/model-method-pathfinder.Rd, man/model-method-sample.Rd, man/model-method-sample_mpi.Rd, man/model-method-variational.Rd, tests/testthat/test-model-output_dir.R
Fix spurious cmdstan config errors when reading CSVs
Andrew Johnson
=> Fix spurious cmdstan config errors

R/fit.R, R/utils.R, inst/include/model_methods.cpp
=> Fix incorrect sizing for `unconstrain_draws()` in some cases

DESCRIPTION, R/data.R, R/utils.R, tests/testthat/test-data.R
Warn user when input data coerced to `int`.
Closes #991
Andrew Johnson
=> Warn on input data int conversion

docs/articles/cmdstanr.html, docs/index.html
**INSERT COPYRIGHT HOLDER HERE**
=> Update web article repo links

R/data.R, tests/testthat/test-data.R
Fixes new errors with passing factor data
Andrew Johnson
=> Fix factor data handling

.github/workflows/R-CMD-check-wsl.yaml, .github/workflows/R-CMD-check.yaml, .github/workflows/Test-coverage.yaml, .github/workflows/cmdstan-tarball-check.yaml, R/install.R
R4.5 and RTools4.5 will be releasing soon, so we need to add handling for the new version. I think we'll probably also need to do another release (just a v0.9, not the full v1.0) so that users can pickup the binaries from R-Universe
Andrew Johnson
=> RTools45 compatibility

.github/workflows/R-CMD-check.yaml
- NA Run unit tests 
R 45 was released so it's now part of the windows release image. This should solve this failure:
https://github.com/katrinabrock/cmdstanr/actions/runs/14448901004/job/40516341197
Demo of fix:
https://github.com/katrinabrock/cmdstanr/actions/runs/14449611217/job/40518751611?pr=5
I think there is still an issue with Mac that this doesn't solve.
Max Planck Institute of Animal Behavior
- Documentation: CC-BY 4.0 …
=> bump release rtools version
