stan-dev/cmdstanr

R/install.R, R/model.R, inst/make_cmdstan.sh
Fixes #37 and #42 
This PR does the following: 
- on windows calls make_cmdstan.sh with `-w` so we can handle window specific stuff
- uses mingw32-make on Windows to build (mandatory in 2.21 due to TBB, its also fine for all previous versions, comes with RTools just like make)
- removes the need for smylinking of cmdstan on install; just extracts to cmdstan/ (was there a reason this wasnt done this way? I might be missing something);
- adds removal of the tar.gz file to make_cmdstan.sh
- on Windows with 2.21+ adds path to TBB lib to the environment variable PATH so we dont need to copy tbb.dll every time in the model exe folders
=> install_cmdstan windows fixes & cleanup, set TBB path

R/model.R, R/utils.R
Fixes #47 
This issue was raised by @bbbales2, thank you for that. Sorry for any inconvenience.
The way I envisioned things before was that the users would set all of their compile time flags through cmdstanr which now that I think of it was probably not the brightest idea. It would cause problems for users coming from cmdstan because it would demand they copy their flags to R.
With this PR users can still handle all their compile time flags directly in make/local. cmdstanr will append any additional flags after the directly set flags. The convenience cmdstanr features (force recompiling of model.o and main.o on changes to the flags) will only be available for flags set through cmdstanr.
=> Dont overwrite users make local flags

R/model.R, man/model-method-compile.Rd, tests/testthat/test-model.R
Closes #50
This PR adds an argument `quiet` (defaulting to `TRUE`) to the `$compile()` method. This means that the standard output and error from CmdStan is suppressed during compilation. The downside to this is that any errors are just generic errors (instead of the content of stderr), so I put in the doc a suggestion to set `quiet=FALSE` if the user encounters an error during compilation and wants to see more of the output. Another option I guess would be to store the stderr output in case there's an error and then return that to the user if necessary?
=> Suppress CmdStan compilation output by default

R/model.R, man/model-method-compile.Rd, tests/testthat/resources/stan/bernoulli_include.stan, tests/testthat/test-model.R
closes #59
This PR adds an `include_paths` argument to the `$compile()` method and uses it with `make` directly by adding `STANCFLAGS += --include_paths`. It didn’t seem necessary to use `make/local`, but @rok-cesnovar do you see any problems with handling the `include_paths` in this way? Would it be better to do it via `make/local` (or some other way)? 
@bbbales2 feel free to chime in as always, but no obligation!
=> Add include_paths argument to $compile() method

R/fit.R, R/install.R, R/model.R, R/utils.R
Fixes #60
Adds the following: 
- R scripts will stop on compile error, which I think is expected behavior. Now scripts continue sampling with previously compiled models.
- will also stop on error in optimize, VI, diagnose and summary
- will always print stderr (warnings and errors) regardless if quiet is set or not
=> Better handling of compile errors

.appveyor.yml, R/args.R, R/fit.R, R/model.R, R/run.R, R/utils.R, man-roxygen/model-common-args.R, man/fit-method-save_output_files.Rd, man/model-method-optimize.Rd, man/model-method-sample.Rd, man/model-method-variational.Rd, tests/testthat/answers/sandbox/README, tests/testthat/teardown-remove-files.R, tests/testthat/test-model-output_dir.R, tests/testthat/test-model-sample.R
Closes #89
* Builds off of the branch for PR #84 so should be reviewed after #84 is merged (the diff for this PR currently looks bigger than it really is since this branch includes all the changes from that one) 
* Adds argument `output_dir` to `$sample()`, `$optimize()`, and `$variational()` methods to control where output and diagnostic csv files are written:
- e.g., `mod$sample(data = stan_data, output_dir = PATH_TO_DIRECTORY)`
- internally `output_dir` is handled by `CmdStanArgs`
- defaults to temporary directory (so default behavior stays the same)
* Added new test file `tests/testthat/test-model-output_dir.R`
* Refactored `copy_temp_files` to separate out generating file names into a different function that can also be called by `$new_files()` method of `CmdStanArgs` object.
Please …
=> Add argument `output_dir`

DESCRIPTION, R/model.R, tests/testthat/test-fit-shared.R
This swaps stan_rdump in for write_stan_json to handle https://github.com/stan-dev/cmdstanr/issues/96. We expect to go back to write_stan_json once cmdstan can handle multidimensional size zero arguments via json.
- [] Run unit tests
Columbia University
=> Switch back to using Rdata temporarily while issue with 0x0s gets resolved for JSON

README.md
I tried to install following the `README` file but got stuck for the lack of the `posterior` package, and then I had to find again in which repository it was. Let's mention it in the `README` while it's not yet on CRAN.
Marco Colombo
=> Mention dependency on posterior package which is not on CRAN yet

R/run.R
Closes #105 
Formats all timediff as seconds.
Rok Češnovar, University of Ljubljana
=> format time diff as seconds in double

DESCRIPTION, R/model.R, tests/testthat/test-fit-shared.R
Reverts stan-dev/cmdstanr#100 since the underlying cmdstan issue will be resolved for 2.22
Closes #109
=> With Cmdstan 2.22+ use JSON by default

R/run.R
Fixes #97 by reverting #99 and adding `try()` to avoid an error. Previous fix in #99 removed the error but introduced a bug where processes were not terminated.
Please describe the purpose of the pull request. 
=> use try to avoid error reported in #97

R/fit.R, tests/testthat/test-fit-mcmc.R, tests/testthat/test-fit-mle.R, tests/testthat/test-fit-vb.R
closes #111
Updates use of `posterior::summarise_draws()` to avoid problems for models fit using optimization and vb. The tests that were failing and commented out now pass. 
Please describe the purpose of the pull request. 
=> fix use of posterior::summarise_draws

R/fit.R
Avoids code duplication in CmdStanMCMC by calling `private$read_csv_(diagnostic_warnings=TRUE)` in `$initialize()`. I added an argument `diagnostic_warnings` to `private$read_csv_` (defaulting to FALSE) so that it can be turned on during initialize but is otherwise off. 
=> avoid duplicating code in $initialize() and private$read_csv_()

R/read_csv.R, tests/testthat/test-csv.R
Fixes #131 
`read_sample_csv` will now stop only if the following args in csv files dont match: 
- num_samples
- num_warmup if save_warmup = 1
- thin
- save_warmup (one csv contains warmup samples, the other doesnt)
This are the args that will cause chains of different length and we cant merge them. If other args dont match it will just give out a warning.
Rok Češnovar
=> Fix csv match check

DESCRIPTION, R/install.R, man/install_cmdstan.Rd
Closes #116
Adds the following: 
- users can install specific releases from any fork, not just the latest release
- ignore release candidates (prerelease = true) when choosing latest (irrelevant right now, but will be useful once we start using release candidates for releases)
- file download is retried 5 times on failure
Rok Češnovar
=> Add release_url to install_cmdstan()

DESCRIPTION, R/utils.R
This PR renames `extract_one_variable_matrix` to `extract_variable_matrix` in accordance with PR https://github.com/jgabry/posterior/pull/63 of posterior. @jgabry are you ok with me merging this PR into cmdstanr so that we can get going with renaming in posterior as well?
=> rename 'extract_one_variable_matrix' to 'extract_variable_matrix'

R/install.R, vignettes/cmdstanr.Rmd
Fixes #145 by:
- replacing `parse_json` with `read_json`. read_json is from jsonlite 1.2.0 which matches our requirement
- adds retries to downloading release files
- move back to using `releases/latest` instead of `releases` as that seems to ignore pre-releases so its fine
Rok Češnovar
=> replaces parse_json with read_json and adds retries to download

R/args.R, R/fit.R, R/model.R, R/read_csv.R, tests/testthat/resources/stan/bernoulli_fp.stan, tests/testthat/test-model-sample.R
Adds fixed_param and extends read_sample_csv to support fixed param runs. Closes #8 
Rok Češnovar
=> Fixed param

R/model.R
Using threads = TRUE warns the user and not stops.
Rok Češnovar
=> Add deprecation warning for threads = TRUE

R/fit.R, R/run.R, tests/testthat/test-failed-chains.R
Fixes #76 
Fit will be returned regardless of the number of chains that finished successfully.
fit$draws(), fit$summary() and all other functions that require results from the CSV files will only read in results from successful chains. Same for cmdstan_summary and cmdstan_diagnose.
fit$latent_dynamics_files(), fit$output_files() , fit$save_latent_dynamics_files() and fit$save_output_files() all have include_failed = TRUE, meaning that the return/save files from failed chains by default. This allows users to read failed chains separately if necessary. …
=> Handle failed chains better

R/model.R, R/run.R
This was the problem @martinmodrak was experiencing. The problem was that we only set the TBB path in the compiling step and if you did a reboot and used a built model it never got set.
You can check that this is the bug by rebooting, force-compiling some unrelated model, and trying to run the previously failing model.
=> Fix Windows run after reboot bug

R/install.R, man/install_cmdstan.Rd, tests/testthat/test-utils.R
This closes #190. I forgot we have the flags argument in `install_cmdstan` so that was not really an issue. I just renamed it to `cpp_options` as that is the name we use in other places. This also fixes a minor issue I observed on Windows with the flags to silence warnings not being recognized properly.
Will merge when tests pass.
=> Rename flags to cpp_options

DESCRIPTION, README.md
cmdstanr and posterior are now on https://mc-stan.org/r-packages/
This updates the install instructions.
`devtools::install_github("jgabry/posterior")` is also not needed even with install_github due to the 
`Additional_repositories` field.
=> Update install instructions

DESCRIPTION, R/fit.R, docs/reference/fit-method-summary.html, docs/reference/index.html, man/fit-method-summary.Rd, tests/testthat/test-failed-chains.R, tests/testthat/test-fit-mcmc.R, tests/testthat/test-fit-mle.R, tests/testthat/test-fit-vb.R
Closes #27 
* Implements a `$print()` method for fitted model objects. Based on a suggestion from Andrew (who doesn't like the way tibbles are printed), the print method is the same as `$summary()` but drops all the weird tibble formatting.
* In the process I also added a `variables` argument to `$summary()` 
To see the difference between print and summary do: 
```r
fit <- cmdstanr_example("logistic")
fit$summary(variables = "beta") # prints with tibble formatting
fit$print(variables = "beta") # prints with regular formatting
```
license the submitted work under …
=> Print method

R/read_csv.R
Fixes #213 by adding two additional suggestions to the vroom functions: 
- the number of lines to skip from the start of the file. This was the main issue for the bug. Vroom gets confused with multiple comments sections (before param, after warmup, and at the end). As we already read these lines we know the exact number of them so we can just skip them
- the ballpark number of the total lines. This does not have to be exact, just narrowing the options a bit. I put 2x(number of warmup+sampling) and it works fine. There is no speed gain if we narrow it further.
By submitting this pull request, the copyright holder is …
=> Bugfix/213 session crash with very large number of parameters in the CSV file

R/fit.R, R/read_csv.R, R/utils.R, tests/testthat/test-csv.R, tests/testthat/test-fit-mcmc.R
fixes #211 
Fixes `matching_variables` and `remaining_columns_to_read` so that variables are returned in the correct order. @rok-cesnovar I made some comments below to explain why I made the changes I did. 
=> Respect variables order

R/fit.R, tests/testthat/test-fit-mcmc.R, tests/testthat/test-fit-vb.R
Fixes #220 
Figures out which rows of the printed data frame will end up being displayed (due to `max_rows` argument) and only computes summary stats for those rows.
Run this same code using the master branch and then using the `only-compute-printed-rows` branch:
```r
tmp_prog <- tempfile(fileext=".stan")
cat("
parameters {
vector[1000] x;
}
model {
x ~ std_normal();
}
", file = tmp_prog)
mod <- cmdstan_model(tmp_prog)
fit <- mod$sample()
fit$print()
```
- Code: BSD 3-clause …
=> print() method: only compute stats for rows that will be printed

man-roxygen/seealso-docs.R, man/CmdStanGQ.Rd, man/CmdStanMCMC.Rd, man/CmdStanMLE.Rd, man/CmdStanModel.Rd, man/CmdStanVB.Rd, man/cmdstan_model.Rd, man/cmdstanr-package.Rd, man/model-method-compile.Rd, man/model-method-generate-quantities.Rd, man/model-method-optimize.Rd, man/model-method-sample.Rd, man/model-method-variational.Rd
Closes #244 
Replaces link to PDF guide with https://mc-stan.org/docs/cmdstan-guide/, which links to the latest html version of the CmdStan guide. 
The only change is to `man-roxygen/seealso-docs.R`. All the other files are auto-generated. 
=> link to online cmdstan guide instead of pdf

.github/workflows/R-CMD-check.yaml, R/read_csv.R
Fixes #249
Uses `utils::read_csv()` if `vroom::vroom()` errors. Throws a warning asking users to report. 
=> use read.csv if vroom fails

.github/workflows/R-CMD-check.yaml, .github/workflows/Test-coverage.yaml, DESCRIPTION, R/install.R, R/model.R, R/path.R, tests/testthat/helper-envvars-and-paths.R, tests/testthat/test-model-compile.R
Cmdstan 2.24 deprecated --include_paths in favor of --include-paths. So we should use that. Fixes #245 
The issue also has a request: 
"It would be convenient if include_paths included the directory of the model file"
This PR does not address that. I am not sure what would be best there. I guess there might be situation where users don't want "." in include paths.
=> Use the hyphened --include-paths stancflag for 2.24+

R/utils.R
Updates the warning about divergences with a bit more information. Once we have something like the interface-agnostic page described at https://discourse.mc-stan.org/t/text-for-warning-message/16928/37?u=jonah then we can simplify this message and just point there. 
To see what the new message looks like run the schools example, which has divergences: 
```
fit <- cmdstanr_example("schools") 
```
```
Warning: 226 of 4000 (6.0%) transitions ended with a divergence.
This may indicate insufficient exploration of the posterior distribution.
Possible remedies include: 
* Increasing adapt_delta closer to 1 (default is 0.8) 
* Reparameterizing the model (e.g. using a non-centered parameterization)
* Using informative or weakly informative prior distributions 
```
Please list the copyright holder …
=> Update divergences warning

R/path.R, R/zzz.R
Closes #265 
When the package is loaded via library it now checks what the latest CmdStan version is to see if it's more recent than the version being used. If it is then there is a message alerting the user (see example below). This slightly but noticeably increase load time because it has to check GitHub. Also, if there is an error checking the version number from GitHub then there is no message.  
```
> library(cmdstanr)
Loading cmdstanr
This is cmdstanr version 0.1.1
- Online documentation and vignettes at mc-stan.org/cmdstanr
- CmdStan path set to: /Users/jgabry/.cmdstanr/cmdstan-2.23.0
- Use set_cmdstan_path() to change the path
A newer version of CmdStan is available. See ?install_cmdstan() to install it.
```
(this …
=> Message at startup if new CmdStan is available

R/zzz.R
closes #274
I think this fixes #274. We forgot about the case when there is no pre-existing CmdStan installation! 
=> fix loading if no previous cmdstan installation

.github/workflows/R-CMD-check.yaml
- MacOS  binaries for R-devel are available again on https://mac.r-project.org/ so we can turn that back on again.
- we can also switch testing to ubuntu 20.04 and I believe r-devel is available now (have to test this one)
- also trying out if windows oldrel is working now
=> Updating Github Actions

NEWS.md, R/args.R, R/fit.R, R/install.R, R/model.R, R/utils.R, tests/testthat/test-model-output_dir.R
Fixes #281 
Originally planned to do this as part of #289 but that might take a bit longer to polish so we can fix this here
=> Fix trailing slash on directories windows bug

NEWS.md, R/fit.R, R/read_csv.R, tests/testthat/test-csv.R, tests/testthat/test-fit-mcmc.R
=> Fix returning draws/sampling diagnostics for warmup with no samples

tests/testthat/test-fit-mcmc.R
This fixes the occasional but annoying macOS CI false positive. 
It turns out the problem is with sampling with 100k iterations we had in one test. Reducing that to 10k fixes the occasional CI failures on MacOS. I ran ~50 tests on my fork and got zero fails. There might be other cases where we are close to the memory limit on the mac agents and we will see those pop-up now. But we now at least know what to look at and that these are in fact false positives.
The segfault that occurred happened in the test where we read the 100k draws in memory. I am assuming the virtual machine runs out of memory. If we really want to test with 100k iterations, the fit would have to be split in a separate test file. I don't think it is necessary to test for 100k so I just reduced it to 10k.
Please list the …
=> Fix macOS CI issue

R/install.R, man/install_cmdstan.Rd, tests/testthat/test-install.R
=> Add version to install_cmdstan

tests/testthat/test-install.R
Fixes #310 
Not sure what codecov does but install tests do not work on Windows in `covr::codecov()`. The version PR added an additional test for installation that needed the skip for windows coverage tests that were added yesterday.
=> Fix windows codecov tests

NEWS.md, R/model.R, R/run.R, man-roxygen/model-common-args.R, man/model-method-optimize.Rd, man/model-method-sample.Rd, man/model-method-variational.Rd, tests/testthat/test-fit-shared.R
The newton optimization method does not respect the refresh arg. This PR ignores all stdout when refresh = 0, which seems logical to me as the only reason someone would use refresh = 0, is when they do not want any info printed.
=> Ignore stdout on refresh=0

R/args.R, R/model.R, man-roxygen/model-common-args.R, man/model-method-generate-quantities.Rd, man/model-method-optimize.Rd, man/model-method-sample.Rd, man/model-method-variational.Rd, tests/testthat/test-fit-shared.R, tests/testthat/test-install.R
=> Add sig_figs argument

README.md, docs/articles/cmdstanr.html, docs/articles/cmdstanr_files/header-attrs-2.3/header-attrs.js, vignettes/cmdstanr.Rmd
@rok-cesnovar @mitzimorris @bob-carpenter Based on feedback in #351 I've made the following edits: 
* Clearly mention in README that CmdStan has to be installed, not just the R package. A link is provided to the Getting Started vignette to avoid duplicating the installation content already in the vignette. 
* Add a link to the toolchain requirements in the installation section of the Getting Started vignette. These requirements change from time to time, so I think it's better to link to the CmdStan guide (https://mc-stan.org/docs/cmdstan-guide/cmdstan-installation.html). Otherwise we'll have to change the information in multiple places every time it gets updated. 
I think I addressed the other points in #351 in my response over there. But if I'm wrong in some of my comments over there we …
=> Update installation instructions

R/run.R
Sets `echo_cmd = FALSE` when using `processx::run()` for `$cmdstan_summary()` and `cmdstan_diagnose()`. There's really no need for us to ever display the command for these methods, it just adds more clutter to the output. 
@mike-lawrence is this what you meant by a "quiet" option in #341? It's still not super "quiet" without echo-ing the command but any quieter and there will be zero printed output which would defeat the purpose of calling it. Or did you really want zero printed output? Or am I totally misunderstanding? ;)
license the submitted work under the …
=> don't echo the cmd when using cmdstan_[summary/diagnose]

NEWS.md, R/model.R, R/read_csv.R, R/run.R, man/model-method-generate-quantities.Rd, man/model-method-optimize.Rd, man/model-method-variational.Rd, tests/testthat/test-model-generate_quantities.R, tests/testthat/test-threads.R
=> Add threading for variational/optimize

R/model.R
=> catch PCH errors with informative message feature

R/data.R, R/model.R, man/model-method-generate-quantities.Rd, tests/testthat/test-data.R, tests/testthat/test-model-generate_quantities.R
=> Accept cmdstanvb, draws_array or draws_matrix as fitted_params

NEWS.md, R/read_csv.R, tests/testthat/resources/csv/model1-1-warmup.csv, tests/testthat/test-csv.R
=> Fix inv_metric()

NEWS.md, R/args.R, R/model.R, man-roxygen/model-common-args.R, man/model-method-generate-quantities.Rd, man/model-method-optimize.Rd, man/model-method-sample.Rd, man/model-method-sample_mpi.Rd, man/model-method-variational.Rd, tests/testthat/test-model-optimize.R
Fixes #388. Adds the remaining (l)bfgs arguments to the optimize method. 
=> add tolerance args for (l)bfgs

NEWS.md, R/data.R, tests/testthat/test-data.R, tests/testthat/test-model-data.R
fixes #401
If model doesn't require data, allow the user to pass in an empty list of data. Previously the user had to leave `data` as NULL or pass in non-empty list. 
=> allow empty data list

R/fit.R
fixes #402
For the print method, adds a new line after the message about using the `max_rows` argument to print more rows.
=> new line after message about max_rows

R/model.R
fixes #400
When detecting problems with the precompiled header, instead of looking for the full message just look for "PCH file" to hopefully catch more cases. We saw an [example on the forum](https://discourse.mc-stan.org/t/struggling-to-get-cmdstan-working-on-mac-os-big-sur/19774/4?u=jonah) where the error message contained "PCH file" but wasn't the same as the full messages we were looking for. 
@rok-cesnovar Is it possible for "PCH file" to appear in a different message that we wouldn't want to catch? If so then maybe we don't want to make this switch, but I'm thinking that's very unlikely right? Just in case, I made the warning message slightly more speculative. 
(this will be you or your assignee, such as a university …
=> only look for "PCH file" not full message

R/knitr.R, R/zzz.R
Fixes a Note from R cmd check that I've been ignoring for a while but we need to fix before submitting to CRAN: 
```
❯ checking R code for possible problems ... NOTE
Found the following assignments to the global environment:
File ‘cmdstanr/R/knitr.R’:
assign(output_var, mod, envir = knitr::knit_global())
```
This is required for the knitr engine so we can't fix this by not doing the assignment. To get around the NOTE I borrowed an idea from https://github.com/yihui/knitr/issues/1824#issuecomment-647333232 to create a function that returns the environment and gets populated with the knitr::knit_global() during .onLoad(). 
By …
=> fix r cmd check NOTE about assignment to global env for knitr

DESCRIPTION, NEWS.md, R/fit.R, R/read_csv.R, man/fit-method-time.Rd, man/read_cmdstan_csv.Rd, tests/testthat/test-csv.R
read_cmdstan_csv now returns time if MCMC CSVs are used.
Rok Češnovar
=> Return time in read_cmdstan_csv for MCMC

.github/workflows/R-CMD-check.yaml, .github/workflows/Test-coverage.yaml, .github/workflows/cmdstan-tarball-check.yaml, R/install.R, tests/testthat/helper-envvars-and-paths.R, tests/testthat/test-csv.R, tests/testthat/test-data.R, tests/testthat/test-install.R, tests/testthat/test-model-sample_mpi.R
Fixes #380 and cleans up our CI: 
- add the use of a Github authentication token for API requests
- always automatically test the latest release without the need to update the URL in Github Actions workflow file (doable now that we added the above)
- we now test MPI in codecov as well
- skip_if_offline checks in some tests required the curl package but was not installed. we now install it manually
- install tests are now also run on codecov
Any user that would get their IP restricted due to too much version checks or other Github API requests can use the new environment variable GITHUB_PAT (personal access token).
By …
=> Add GITHUB_PAT for repeated access to Github API and a CmdStan tarball check

R/csv.R, R/fit.R, R/utils.R, tests/testthat/test-fit-mcmc.R, tests/testthat/test-utils.R
We should not be running posterior::bind_draws when looping over the chains but instead call it a single time once we read in all chains.
For this example:
```r
library(cmdstanr)
model_code <- "
parameters {
real k;
}
transformed parameters {
real x[20000] = rep_array(k, 20000);
}
model {
k ~ normal(0, 1);
}
"
model_file <- write_stan_file(model_code)
mod <- cmdstan_model(model_file)
fit <- mod$sample(iter_sampling = 2000, validate_csv = FALSE, chains = 4)
start <- Sys.time()
f <- fit$draws()
print(Sys.time() - start)
```
the $draws() call goes from 28s to 19s. There is no difference for 1 chain.
Rok Češnovar
By submitting this pull request, the …
=> Faster CSV read with multiple chains

.github/workflows/R-CMD-check.yaml, .github/workflows/Test-coverage.yaml, .github/workflows/cmdstan-tarball-check.yaml
This addresses the following `yamllint` errors/warnings for all `CmdStanR` GitHub Actions workflows:
> yamllint -f parsable .github/workflows/R-CMD-check.yaml
```
.github/workflows/R-CMD-check.yaml:1:1: [warning] missing document start "---" (document-start)
.github/workflows/R-CMD-check.yaml:1:1: [warning] truthy value should be one of [false, true] (truthy)
.github/workflows/R-CMD-check.yaml:22:33: [error] too many spaces after comma (commas)
.github/workflows/R-CMD-check.yaml:23:33: [error] too many spaces after comma (commas)
.github/workflows/R-CMD-check.yaml:27:33: [error] too many spaces after comma (commas)
.github/workflows/R-CMD-check.yaml:28:33: [error] too many spaces after comma (commas)
.github/workflows/R-CMD-check.yaml:29:33: [error] too many spaces after comma (commas) …
```
=> GHA: yaml: Lint all workflows

R/zzz.R
Without `knitr` installed:
```
══ Testing test-knitr.R ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
[ FAIL 0 | WARN 0 | SKIP 3 | PASS 0 ]
── Skip (test-knitr.R:4:3): eng_cmdstan throws correct errors ─────────────────────
Reason: knitr cannot be loaded
── Skip (test-knitr.R:10:3): eng_cmdstan works ─────────────────────────────────
Reason: On CRAN
── Skip (test-knitr.R:25:3): register_knitr_engine works with and without override ─────────────────────
Reason: knitr cannot be loaded
[ FAIL 0 | WARN 0 | SKIP 3 | PASS 0 ]
```
With `knitr` installed:
```
══ Testing test-knitr.R ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
[ FAIL 0 …
```
=> Check for knitr installation before loading env

NEWS.md, R/args.R, tests/testthat/test-model-init.R
Addresses #451 (& stan-dev/cmdstan#966)
Please describe the purpose of the pull request. 
Michael A. Lawrence
=> Add check for inits named with square brackets

R/install.R, R/run.R
Fixes #444 and fixes #405 by adding a suggestion for using `$output()` in case of failed chains and to improve the install message 
from `"The CmdStan toolchain is setup properly!"` to 
`"The C++ toolchain required for CmdStan is setup properly!"`
Rok Češnovar
=> Improve error and informational messages

NEWS.md, R/csv.R, tests/testthat/test-fit-shared.R, tests/testthat/test-model-compile.R
This fixes issue with reading in CSV files for models with spaces in name. Issue reported [here](https://discourse.mc-stan.org/t/cmdstanr-cannot-find-fit-output-files-if-stan-file-has-a-space-in-name/20710).
Rok Češnovar
=> Fix issue with reading in CSV for models with spaces in name

R/model.R, tests/testthat/test-model-compile.R
=> Add a check for a folder with model's name

R/model.R, tests/testthat/helper-custom-expectations.R, tests/testthat/test-knitr.R, tests/testthat/test-model-compile.R
Omit compilation messages "Compiling Stan program..." and "Model executable is up to date!" for non-interactive R sessions. Fixed #429.
Eli Lilly and Company
=> Suppress some compilation messages in non-interactive R sessions

.github/workflows/R-CMD-check.yaml, .github/workflows/Test-coverage.yaml
This PR uses the [cache action](https://github.com/actions/cache) to avoid redundant installations of CmdStan in GitHub Actions workflows. I only implemented it in `R-CMD-check.yaml` and `Test-coverage.yaml` because it looks like `cmdstan-tarball-check.yaml` has its own way of only running when CmdStan updates (is that right?). Addresses #463.
Eli Lilly and Company
=> Cache installation of CmdStan in check and coverage workflows

DESCRIPTION, NEWS.md, R/path.R, man/set_cmdstan_path.Rd, tests/testthat/test-path.R
In this PR, `cmdstan_version(error_on_NA = FALSE)` returns `NULL` if the CmdStan path is not set. The default `error_on_NA` is `TRUE`, which is the original behavior. Fixes #467.
Eli Lilly and Company
=> New error_on_NA argument for cmdstan_version()

R/fit.R, vignettes/cmdstanr.Rmd
closes #469
Allows `options(cmdstanr_max_rows = value)` to set `max_rows` argument of print method for an entire R session (or until changing the option). 
=> global max_rows option for print method

R/csv.R, tests/testthat/resources/csv/bernoulli-3-diff_params.csv, tests/testthat/resources/csv/model1-1-dense_e_metric.csv, tests/testthat/resources/csv/model1-2-dense_e_metric.csv, tests/testthat/resources/csv/model1-3-diff_args.csv
This PR is part 1 of addressing #445. It refactors the csv.R to make the subsequent changes in the next PR easier to integrate. I split this up to 
The ideas behind the refactor: 
- read in all metadata first and check it before reading in samples
- do all the column selection logic outside the loop before reading in samples
- read in sampler diagnostics and the rest in separate reads (makes it more RAM friendly when subsetting later - avoids copies)
- do most of the method-type logic near the return not in the CSV reading loop 
Rok Češnovar
license the submitted work under the …
=> Refactor csv.R

R/args.R, R/csv.R, man-roxygen/model-common-args.R, man/model-method-generate-quantities.Rd, man/model-method-optimize.Rd, man/model-method-sample.Rd, man/model-method-sample_mpi.Rd, man/model-method-variational.Rd, tests/testthat/test-csv.R, tests/testthat/test-failed-chains.R, tests/testthat/test-model-sample.R
Right now, cmdstanr sets different seeds for each of the cmdstan process call even if only one seed is given.
```
fit <- mod$sample(..., seed = 2)
```
will set seeds 2,3,4,5 for the 4 chains. This is not ok in the case where transformed uses any _rng functions as
that means that the 4 chains would not have the same data. Even if we set the same seed for all chains, the 
seed used in the rest of the model is actually the seed with a stride defined by the id. See https://github.com/stan-dev/stan/blob/develop/src/stan/services/util/create_rng.hpp#L27
So what we need to do is set the same seeds for all subprocesses.
Test model:
```stan
transformed data {
int N = 100;
vector[N] a;
for (i in 1:N) {
a[i] = uniform_rng(0, 1);
}
}
parameters {
real y;
}
model {
y ~ std_normal();
}
generated …
```
=> Fix the use of seed for multi chain sampling

R/model.R
A bit of minor cleanup of argument checking and some other minor code simplifications in `model.R`. These changes are mostly cosmetic, I just think the resulting code in `model.R` is nicer to read (it may be hard to tell from looking at the diff, so you may have to open the `model.R`  file and look at the methods to notice). 
=> Cleanup CmdStanModel argument checks and other minor code simplifications

.github/workflows/R-CMD-check.yaml, DESCRIPTION, R/example.R, R/fit.R, R/knitr.R, R/utils.R, tests/testthat/test-example.R, tests/testthat/test-utils.R
* Moves rlang package from Imports to Suggests (it's only required if `basename` isn't specified)
* renames the `suggest_package()` internal function to `require_suggested_package()`, which is why it actually does
=> Move rlang to suggests

R/data.R, man-roxygen/model-common-args.R, man/model-method-diagnose.Rd, man/model-method-generate-quantities.Rd, man/model-method-optimize.Rd, man/model-method-sample.Rd, man/model-method-sample_mpi.Rd, man/model-method-variational.Rd, man/write_stan_json.Rd
Documents the different conversions (e.g. list -> array) performed by `write_stan_json()`. I was going to add a note about this issue described in #513 but I decided not too since @rok-cesnovar pointed out that we can solve that problem automatically using the new info about types provided by Stan v2.27. 
=> document conversions performed by write_stan_json

.github/workflows/R-CMD-check.yaml, .github/workflows/Test-coverage.yaml, .github/workflows/cmdstan-tarball-check.yaml, NEWS.md, R/install.R, R/path.R, R/zzz.R, man/cmdstan_default_install_path.Rd, man/cmdstan_default_path.Rd, man/install_cmdstan.Rd, man/set_cmdstan_path.Rd, vignettes/cmdstanr.Rmd
Closes #454 
Changes default directory to `.cmdstan` instead of `.cmdstanr` so that CmdStanPy and CmdStanR can use same installation. If `.cmdstan` isn't found we still look for `.cmdstanr`, but we should eliminate that for version 1.0. 
=> Change default directory to .cmdstan

NEWS.md, R/data.R, R/install.R, R/model.R, R/run.R, R/utils.R, tests/testthat/test-model-compile.R
Fix #517 by applying the suggestion by @martinmodrak. Fixes #493.  Also a bit of cleanup (see comment).
Rok Češnovar
=> Bugfix clearing stdout stderr on finish & cleanup

R/install.R
Fixes #503 
I didnt find a way to add a test as we dont have ARM machines to test this with so existing install tests on x86 will have to suffice. I did try it on an AWS ARM machine and it works.
Rok Češnovar
=> Install Linux ARM tarball automatically

NEWS.md, R/model.R, R/run.R
=> Add checks for NA in return status

R/csv.R, R/fit.R, tests/testthat/test-csv.R
Fixes #504 
This keeps the old $model_params as well but then remove it for the 1.0 release.
Rok Češnovar
=> Rename `fit$metadata()$model_params` to `fit$metadata()$variables`

R/args.R, R/data.R, R/model.R, tests/testthat/test-fit-shared.R
Fixes #550 
I want to rework this later so the --info stanc3 is not called more than once, but this fixes the issue for now, even if its a bit verbose solution.
Rok Češnovar
=> Fix issue with included Stan files

R/args.R, R/data.R, R/model.R, tests/testthat/test-data.R
Refactors the changes made in https://github.com/stan-dev/cmdstanr/pull/553 and some done prior to that. The main change is that everything now runs through $variables() and thus we wont call stanc3 multiple times.
Rok Češnovar
=> Refactor the use of $variables() for processing data and inits

.github/workflows/Test-coverage.yaml
Test coverage is using Ubuntu 16.04 (~~I forget why we use that~~ we use it because there is an issue with 20.04), while other tests run with the latest Ubuntu). Seems that Github no longer has those machines, so we need to bump up. Once tests pass I will merge this.
Rok Češnovar
=> Bump GHA Linux test runner version

R/data.R, tests/testthat/test-data.R
#538 introduced a bug that caused issues reported on Discourse (https://discourse.mc-stan.org/t/mismatch-in-number-of-dimensions-declared-and-found/24599). This PR fixes that bug.
Rok Češnovar
=> Fix handling integers

.github/workflows/R-CMD-check.yaml, .github/workflows/Test-coverage.yaml
Increases the CmdStan version used in the unit tests. We should also figure out if we still want to hardcode the version number or just instal the latest automatically. I'm guessing we were hardcoding it for a reason? 
=> use CmdStan 2.28.1 in tests

DESCRIPTION, R/cmdstanr-package.R, R/model.R, R/zzz.R, man-roxygen/model-common-args.R, man-roxygen/model-sample-args.R, man/cmdstan_model.Rd, man/cmdstanr-package.Rd, man/model-method-compile.Rd, man/model-method-diagnose.Rd, man/model-method-generate-quantities.Rd, man/model-method-optimize.Rd, man/model-method-sample.Rd, man/model-method-sample_mpi.Rd, man/model-method-variational.Rd
Doing some doc edits to prepare for v1.0. I also changed the package startup messages a bit. 
Old version: 
```
This is cmdstanr version 0.4.0.9000
- Online documentation and vignettes at mc-stan.org/cmdstanr
- CmdStan path set to: /Users/jgabry/.cmdstan/cmdstan-2.28.1
- Use set_cmdstan_path() to change the path
``` 
New version: 
```
This is cmdstanr version 0.4.0.9000
- CmdStanR documentation and vignettes: mc-stan.org/cmdstanr
- CmdStan path: /Users/jgabry/.cmdstan/cmdstan-2.28.1
- CmdStan version: 2.28.1
```
@rok-cesnovar What do you think of this change? If you prefer the old version we can keep it, or if you have suggestions for the new version I can add those. 
(this will be you or your assignee, such as a university …
=> edits to doc and startup messages

tests/testthat/test-install.R
This PR should _not_ be merged, just using it to trigger the CI.  I'm trying to investigate the question in #589 as to why a test that should have failed in all runs only failed in test coverage on linux. This attempts to recreate the problem.
=> try to get test to error in order to investigate #589

R/model.R, man/cmdstan_model.Rd, man/model-method-compile.Rd
Closes #556. Instead of adding the compile arguments explicitly to `cmdstan_model` this PR improves the documentation of the `...` argument to make it more clear what options are available (e.g., specifying the directory to store the executable).  
=> Make cmdstan_model doc more clear about compile options

R/model.R
Adds a fix for an M1 macOS issue reported by @spinkney. See https://discourse.mc-stan.org/t/m1-mac-issues/25453/6 for more.
The fix is essentially deleting the executable before we copy it over. For some reason (I will admit I am not exactly sure why this helps) just overwriting it causes issues. But an extra delete before an overwrite seems fine to me, so I am fine with adding this even though I am not 100% why it helps :)
Rok Češnovar
- Documentation: CC-BY …
=> Fix for M1

vignettes/cmdstanr-internals.Rmd, vignettes/cmdstanr.Rmd, vignettes/profiling.Rmd, vignettes/r-markdown.Rmd
For some reason, in Github Actions, when running the vignettes, it selects the new Windows UCRT toolchain (the new RTools 4v2 has two available toolchains). I have not been able to find out why exactly this happens and the rest of our tests work fine. 
This just adds a call to fix the toolchain before running the rest of the vignette. I am going to merge this with the tests passing until we find a nicer fix for this probem. This does not affect our Windows users otherwise.
Rok Češnovar
- Code: BSD 3-clause …
=> Temporary fix for vignettes on GHA

DESCRIPTION, vignettes/r-markdown.Rmd
Use the new verbatim engine from [knitr 1.37](https://github.com/yihui/knitr/releases/tag/v1.37) for cleaner embedded code chunks in the source R Markdown document.
Mikhail Popov
=> Use verbatim engine for embedded code chunks

tests/testthat/test-utils.R
Fixes a brittle test that relied on "\n" in the output. It failed if the output had "\r\n".
Rok Češnovar
=> Fix windows output message test

R/csv.R
Fixes #562 
We cant really add tests for this. I did try this script out on Windows Github Actions instances: 
```r
fit <- cmdstanr::cmdstanr_example()
a <- Sys.which("grep.exe")
dir.create("~/test test")
b <- cmdstanr:::repair_path("~/test test")
file.copy(a, b)
grep_path <- paste0('"', file.path(b, "grep.exe"), '"')
fread_cmd <- paste0(grep_path, " -v '^#' --color=never '", fit$output_files()[1], "'")
t <- data.table::fread(
cmd = fread_cmd,
data.table = FALSE
)
```
and it works fine with this fix and doesn't without it.
Rok Češnovar
license the submitted work under the following …
=> Use quotes with path to grep.exe on Windows

R/install.R, R/model.R, docs/reference/install_cmdstan.html, man/install_cmdstan.Rd, tests/testthat/test-model-compile.R, tests/testthat/test-utils.R
Fixes handling of user_header when it is supplied as part of cpp_options.
Fixes #612 
Rok Češnovar
=> Fix `user_header` handling

DESCRIPTION
When installing, I get the following warning: 
```
NB: this package now depends on R (>= 3.5.0)
WARNING: Added dependency on R >= 3.5.0 because serialized objects in
serialize/load version 3 cannot be read in older versions of R.
File(s) containing such objects:
‘cmdstanr/tests/testthat/answers/model-code-output.rds’
```
So I just added "Depends: R >= 3.5.0". We could go and do something else as opposed to `.rds` file, but R 3.4 is so obsolete, I don't think it's worth it.
Rok Češnovar
- Code: BSD 3-clause …
=> Add Depends: R >= 3.5.0

docs/articles/r-markdown.html, vignettes/r-markdown.Rmd
I got the verbatim chunks working again. Actually I think they never stopped working, I just had an old version of knitr installed. 
=> r-markdown.Rmd: use verbatim chunks again

DESCRIPTION, NEWS.md, R/fit.R, R/utils.R, man/CmdStanMCMC.Rd, vignettes/profiling.Rmd
I was thinking that while we decide what to do about #582 we should probably error when the `draws_rvars` format is used instead of returning the wrong thing. What do you think @rok-cesnovar? The error message I added suggests using `posterior::as_draws_rvars` for now. 
=> temporarily disable rvars

R/path.R, R/zzz.R, man/cmdstan_default_path.Rd, man/cmdstan_model.Rd, man/set_cmdstan_path.Rd
Fixes #638 
Expands the use of the `CMDSTAN` environment variable so that if a valid CmdStan installation is not found in the `CMDSTAN` path, it is used as the top level installation folder (cmdstan installations are a level below).
To test run:
```r
Sys.setenv("CMDSTAN" = "/top/level/folder/of/cmdstan/installs")
library(cmdstanr)
```
Rok Češnovar
=> Expand the use of CMDSTAN variable 

R/path.R
fixes #650
In `cmdstan_default_path()` ignore directories inside `.cmdstan` that don't start with `"cmdstan-"`.  
=> in cmdstan_default_path() ignore other directories in .cmdstan

R/csv.R
In the edge case where the users do not have `grep.exe` in their system path, we need to wrap the `Sys.which()` call in the with_path call just like we do the rest of the system calls.
Rok Češnovar
=> Fix finding grep.exe path on Windows

R/utils.R
If the calculate ebfmi was NaN, the post-processing failed. This should fix that and thus should fix #657 and fix #652 
Rok Češnovar
=> Fix ebfmi calculation to handle NaN

NEWS.md, R/example.R, tests/testthat/test-example.R, tests/testthat/test-model-compile.R
See https://discourse.mc-stan.org/t/problem-using-cmdstanr-write-stan-file-dir-with-brms/28117 for reasons
Essentially using  ~ with the cmdstanr_write_stan_file_dir option did not work. This fixes that.
Rok Češnovar
=> Fix use of tilde with cmdstanr_write_stan_file_dir

.github/workflows/R-CMD-check.yaml, .github/workflows/Test-coverage.yaml, .github/workflows/cmdstan-tarball-check.yaml, tests/testthat/test-model-compile.R
A couple of tests are failing for the 4.2 and devel Windows tests in CI (GHA) with some recent changes in the Rtools42 toolchain. Attempting to address them.
Rok Češnovar
=> CI Windows fixes

R/install.R
Fixes the toolchain check by normalizing paths before comparing them, avoiding comparing long and short paths, which leads to false positives.
Rok Češnovar
=> Windows fix: Normalize paths before comparing them

R/run.R
=> Fix fit$time() for the case when chains fail

R/model.R, tests/testthat/test-model-variables.R
Naive attempt to tackle #680.
**Approach**
Adapt the `CmdStanModel$variables()` query method in such a way that it returns either `private$include_paths_` or `private$precompile_include_paths_`. 
**Alternative that was considered:**
During call to `model_variables()`, make the value passed to the  `include_paths` argument dependent on the state of the model. I.e., if no executable is present, insert `private$precompile_include_paths_`, and otherwise `self$include_paths()`.
Concerns: it seems somewhat not optimal to query the state of the model (compiled / not compiled) via the existence of the executable, but I saw this approach also elsewhere in the code.
***
(this will be …
=> `mod$variables` works w includes in precompile state (fix #680)

vignettes/articles-online-only/opencl.Rmd
Fixes broken OpenCL support link, which appears to be this instead http://mc-stan.org/math/d0/d8f/opencl_support.html
Closes https://github.com/stan-dev/cmdstanr/issues/685
Eric Leung
=> Update broken link for Stan OpenCL support page

R/model.R
Running the following script:
```
library(cmdstanr)
file <- system.file("logistic.stan", package = "cmdstanr")
model <- cmdstan_model(stan_file=file, compile=FALSE)
model$check_syntax(stanc_options = list("debug-mem-patterns"))
```
produced the following output:
```
vector[K] beta: AoSStan program is syntactically correct
```
which is missing a newline. This PR fixes this issue. This was reported by @avehtari.
Rok Češnovar
- Documentation: CC-BY 4.0 …
=> Add newline to check syntax output

R/fit.R, R/model.R, R/utils.R, tests/testthat/test-model-expose-functions.R
This PR adds the `expose_functions()` method to the `CmdStanModel` class so that functions can be exposed to R without fitting any models first
Andrew Johnson
=> Allow exposing functions without sampling

R/fit.R, R/utils.R, tests/testthat/test-model-expose-functions.R, tests/testthat/test-model-methods.R
There was a bug with the model methods and exposed functions wherein running `init_model_methods()` on a `CmdStanFit` object would overwrite the model methods from all `CmdStanFit` objects that came from the same `CmdStanModel`.
This was because the environment was being passed by reference from the `CmdStanModel` object when initialising each `CmdStanFit`, so every fit object was pointing to the same environment.
This PR updates the initialisation to create a new environment and copy the contents, as well as adding a test to check for this in the future
Andrew Johnson
license the …
=> Bugfix - Deep copy method/function environments

R/fit.R, R/utils.R, inst/include/hessian.cpp, man/cmdstanr-package.Rd, man/fit-method-hessian.Rd, tests/testthat/test-model-methods.R
This PR updates the `hessian()` method with an additional argument for whether to include jacobian adjustments from parameter constraints - this makes the method now consistent with the `log_prob` and `grad_log_prob` methods.
Andrew Johnson
=> Add option for including jacobian adjustments in hessian method

R/csv.R, R/utils.R
Improve the efficiency of variable matching to fix #735. This is done by first checking for exact matches and removing any matches from the following loop.
As far as I can tell this retains the exact same functionality. The example in #[735](https://github.com/stan-dev/cmdstanr/issues/735#issue-1568907236) runs in under 10s vs. >2mins before. All relevant tests seem to pass.
Sebastian Funk
=> Improve efficiency of variable matching

R/utils.R, tests/testthat/test-model-expose-functions.R
This PR addresses #740 to fix exposing functions with `int` return types. I've also expanded the test to more thoroughly assess compatibility with different types
Andrew Johnson
=> Fix exposing functions with int return types

R/install.R, tests/testthat/test-install.R
This PR updates the file downloading functions to respect the `quiet` argument from an `install_cmdstan()` call, and also to print the actual error message if the download fails.
This will hopefully help with debugging issues like #731
Andrew Johnson
=> Add verbosity to download output and errors

R/model.R, R/utils.R, tests/testthat/test-model-expose-functions.R
This PR closes #713. Currently `expose_functions()` fails with an uninformative error message if external c++ is used. This is due to a bug in `stanc3`, and after [this PR](https://github.com/stan-dev/stanc3/pull/1298) the generated code will be compatible.
This PR adds a simple version check when exposing external functions
Andrew Johnson
=> Add version check when exposing external functions

R/model.R, R/run.R, man-roxygen/model-sample-args.R, man/model-method-sample.Rd, man/model-method-sample_mpi.Rd, tests/testthat/test-model-sample.R
This PR addresses #718 and #646 by adding a `show_exceptions` argument to the `sample()` and `sample_mpi()` methods, and also expands the use of `show_messages=FALSE` to completely suppress all printing of non-errors.
Andrew Johnson
=> Update handling of show_messages, add show_exceptions

.github/workflows/R-CMD-check.yaml, R/install.R, R/utils.R
There was a report on the forum that `cmdstanr`'s toolchain checks weren't working with RTools43, this PR updates the functions to correctly detect the RTools42 vs RTools43
Andrew Johnson
=> Rtools43 support

R/install.R
Building cmdstan versions < 2.31 fails on M1/M2 macs due to a makefile setting which has [since been patched](https://github.com/stan-dev/cmdstan/pull/1127). This PR adds the automatic updating of the `stanc` makefile where necessary so that M1/M2 users can install older versions of cmdstan.
I've also added the `-Wno-deprecated-declarations` flag to suppress the warnings [coming from Boost](https://discourse.mc-stan.org/t/running-cmdstan-on-ventura/30948/11)
Andrew Johnson
- Code: BSD 3-clause …
=> Add stanc M1 make patch, suppress boost warnings

R/model.R, tests/testthat/test-model-compile.R
This PR fixes #774 by using `self$include_paths() ` instead of `private$precompile_include_paths_` in the methods `check_syntax` and `format`. This is because the latter only holds the `include_paths` if the model has not been compiled yet. As a result, it is now possible to call these methods on compiled models with include statements without getting a syntax error from `stanc`. For `format`, this has currently not been possible at all, for `check_syntax`, you always had to use the `include_paths` argument of the function even if the same, default `include_paths` were used.
The PR also adds tests for include_paths in `check_syntax` and `format` on compiled models, but I am not sure if these are desired as they require compilation of the example model during testing.
This is my first PR …
=> Fix model$format and model$check_syntax for compiled models with include-paths

tests/testthat/helper-custom-expectations.R, tests/testthat/test-json.R
Suppresses the CI failures due to `jsonlite` floating point bug and Windows-specific interactive message printing until they can be resolved
Andrew Johnson
=> Temporarily suppress CI failures

.github/workflows/R-CMD-check.yaml, R/fit.R, vignettes/posterior.Rmd
This enables cmdstanr to install on R versions <= 4.0.  I've tested on 4.0, but not explicitly on earlier versions. Can close https://github.com/stan-dev/cmdstanr/issues/788
**NCX, 2443 Fillmore St. #380-1418, San Francisco, CA 94115**
=> replace \ with function

DESCRIPTION, NEWS.md, R/args.R, R/model.R, man/model-method-optimize.Rd, tests/testthat/test-model-optimize.R
Adds `jacobian` argument to `optimize` method. 
Closes #761 and paves the way for #760 (adding Laplace sample)
=> enable jacobian argument for optimization

R/utils.R, inst/include/model_methods.cpp, tests/testthat/test-model-methods.R
Fixes #793 by allowing the model methods to be initialised for models with no input data
Andrew Johnson
=> Fix init_model_methods for models with no data

vignettes/cmdstanr.Rmd, vignettes/posterior.Rmd
Fixes #803 now that stan-dev/posterior#295 is merged. We can revert the hack I used in the vignettes to avoid weird print output when using the summary method.
=> revert vignette formatting hacks

vignettes/cmdstanr-internals.Rmd
- [n/a] Run unit tests (this PR only modifies a vignette)
As proposed by @jgabry at https://github.com/stan-dev/cmdstanr/issues/738#issuecomment-1660632765, this PR documents one way to pre-compile Stan models in a CmdStanR-powered R package. [`instantiate`](https://github.com/wlandau/instantiate) is still in its early days, and I am not sure how to deal with the compiler issues we will inevitably face going forward (c.f. https://github.com/stan-dev/cmdstanr/issues/787, https://github.com/wlandau/instantiate/issues/1). But there are good reasons to pre-compile Stan models in an R package, and this is a start using the modern CmdStan-based tooling.
> Please list the copyright holder for the work you are submitting
> (this will be you or your assignee, such as a university or company):
Eli …
=> Document a CmdStan-focused way to pre-compile Stan models in R packages

vignettes/cmdstanr.Rmd
- [n/a] Run unit tests
As discussed in #340, this PR describes how to efficiently save model fit objects.
> Please list the copyright holder for the work you are submitting
> (this will be you or your assignee, such as a university or company):
Eli Lilly and Company
> By submitting this pull request, the copyright holder is agreeing to
> license the submitted work under the following licenses:
> 
> - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
> - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)
=> Describe how to efficiently save model fit objects

R/model.R, R/utils.R, tests/testthat/test-model-expose-functions.R
Resolves the issues seen when trying to expose Stan functions with a precompiled Stan model
Andrew Johnson
=> Give informative error when exposing stan functions with precompiled model

R/utils.R, tests/testthat/test-model-methods.R
Resolves #821 by fixing the handling of container dimensions in `variable_skeleton()`
Andrew Johnson
=> Fix variable_skeleton() with containers

R/run.R
closes #826
In `.run_diagnose` we were printing stdout twice instead of stdout one and stderr once. 
=> change duplicate stdout_file to stderr_file

R/install.R, R/utils.R
The current install process only downloads the correct release tarball for non-x86_64 if the combination is `Linux+arm64`. This PR updates the detection to correctly handle other architectures on Linux and WSL
Andrew Johnson
=> Update linux/wsl detection for install arch

R/args.R, tests/testthat/test-model-init.R
Resolves the bug report in #855, which identified a more general issue that passing initial values for single-element containers would fail due to the `auto_unbox` setting in `jsonlite` treating them as scalars, resulting in `cmdstan` throwing a dimension-mismatch error.
This PR updates the processing of init-lists to check whether the initial value is for a single dimension-container and then format the value appropriately
Andrew Johnson
- Documentation: CC-BY 4.0 …
=> Fix handling of single-length inits for containers

R/utils.R, inst/include/rcpp_tuple_interop.hpp, tests/testthat/test-model-expose-functions.R
Reported in #859, `Rcpp` doesn't support converting `std::tuple<>` types to/from R. This PR adds the specialisations necessary for `Rcpp`, as well as tests for exposing tuple functions.
Andrew Johnson
=> Add support/tests for exposing functions with tuples

R/utils.R, tests/testthat/test-model-expose-functions.R
We need a very minor tweak to our expose functions routines for supporting complex types (literally 1 line). This PR makes that change and adds tests handling complex types and arrays/tuples
Andrew Johnson
=> Add support/tests for exporting functions with complex types

R/install.R, man/install_cmdstan.Rd, tests/testthat/test-install.R
Closes #865 by adding the option to install cmdstan from a downloaded release archive:
```r
install_cmdstan(release_file = "./cmdstan-2.33.1.tar.gz")
```
Andrew Johnson
=> Add option for installing from release archive

R/fit.R, man/fit-method-grad_log_prob.Rd, man/fit-method-hessian.Rd, man/fit-method-log_prob.Rd, tests/testthat/test-model-methods.R
Closes #877 
Deprecates argument `jacobian_adjustment` in favor of `jacobian` to be consistent with `optimize` and `laplace`. Based on feedback from @avehtari. This affects `log_prob`, `grad_log_prob` and `hessian`. 
=> Rename `jacobian_adjustment` argument to `jacobian`

R/install.R, R/zzz.R
Addresses #889
Allows the `latest_released_version()` function to pass-through arguments to the `download_with_retries()` function. This is to avoid the latest version check from retrying 5 times on package load when the user does not have internet access (or a similar firewall issue)
Andrew Johnson
=> Allow latest version check to take retries arg

R/utils.R
The `cmdstanr` diagnostic threshold for low E-BFMI is 0.2, while the [cmdstan threshold is 0.3](https://github.com/stan-dev/cmdstan/blob/430e382e776f5043efdc869fefccef3179ba778e/src/cmdstan/diagnose.cpp#L153)
Andrew Johnson
=> Align ebfmi threshold with cmdstan

R/model.R, R/run.R, man-roxygen/model-common-args.R, man-roxygen/model-sample-args.R, man/model-method-laplace.Rd, man/model-method-optimize.Rd, man/model-method-pathfinder.Rd, man/model-method-sample.Rd, man/model-method-sample_mpi.Rd, man/model-method-variational.Rd, tests/testthat/test-fit-shared.R
Closes #884 by adding the new `show_messages` and `show_exceptions` arguments to all fitting methods
Andrew Johnson
=> Add show_messages and show_exceptions arguments to all methods

DESCRIPTION, R/fit.R, R/utils.R, inst/include/hessian.cpp, inst/include/rcpp_eigen_interop.hpp, man/cmdstanr-package.Rd, man/fit-method-init_model_methods.Rd
We currently have `RcppEigen` as a `suggests` for use with the model methods and function exports. However, given that we already have the Eigen headers in the cmdstan install, we only need the methods for converting between R and C++ Eigen types. 
Since only a reduced subset of Eigen types are exposed via Stan (`Eigen::Matrix<>`), this is fairly simple to to handle ourselves.
Andrew Johnson
=> Drop RcppEigen dependency, implement basic Eigen -> C++ interop

tests/testthat/test-model-laplace.R, tests/testthat/test-model-optimize.R
Updating argument tests to account for changes in https://github.com/stan-dev/cmdstan/pull/1243
Andrew Johnson
=> Fix tests with v2.34.1

R/args.R, R/model.R, man/cmdstanr-package.Rd, man/model-method-pathfinder.Rd, tests/testthat/test-model-pathfinder.R
Adds the `psis_resample` and `calculate_lp` arguments to pathfinder
Simons Foundation
=> update pathfinder args for psis_resample and lp_calculate

R/fit.R, man/fit-method-loo.Rd, tests/testthat/test-fit-mcmc.R
Fixes a failing test and updates some doc affected by the latest loo package release. 
=> Update doc and tests after latest loo pkg release

R/args.R, tests/testthat/test-model-init.R
closes #912
Adds a global option to turn off warning about partial initial value specification. When `options(cmdstanr_warn_inits=TRUE)` (the default) the warning message now looks like this, with a new line about disabling the warning: 
```
Init values were only set for a subset of parameters. 
Missing init values for the following parameters:
alpha, beta
To disable this message use options(cmdstanr_warn_inits = FALSE).
```
When `options(cmdstanr_warn_inits=FALSE)` there is now no message at all. 
- Code: …
=> Global option for turning off warning for partial initial values

man-roxygen/model-common-args.R, man/model-method-diagnose.Rd, man/model-method-generate-quantities.Rd, man/model-method-laplace.Rd, man/model-method-optimize.Rd, man/model-method-pathfinder.Rd, man/model-method-sample.Rd, man/model-method-sample_mpi.Rd, man/model-method-variational.Rd
=> Clarify in doc that for MCMC `output_dir` contains one file per chain

R/args.R, R/fit.R, tests/testthat/test-model-sample-metric.R
Fixes #934. Now it checks in inv_matrix() function whether the input is a scalar for each chain, and if so, makes it an array with dimension 1. It also corrects the behavior of diag() when matrix=TRUE, which previously produced an empty matrix with a scalar inv_metric.
**Vencislav Popov**
=> Fix incorrect format of inv_metric when only 1 parameter in model

.github/workflows/R-CMD-check.yaml, tests/testthat/test-fit-mle.R, tests/testthat/test-fit-shared.R, tests/testthat/test-model-laplace.R, tests/testthat/test-model-methods.R, tests/testthat/test-model-sample.R
Removes R version 3.6 from Github Actions checks since we will now require at least R 4.0 with future versions of CmdStanR. 
I also updated few tests to get rid of some warnings in the testthat output. 
=> Don't test on R 3.6 anymore

vignettes/cmdstanr.Rmd, vignettes/posterior.Rmd
https://github.com/stan-dev/cmdstanr/issues/183
Closes #632 and closes #183
Better documents how to obtain structured output similar to rstan::extract() using a combination of cmdstanr and posterior. 
=> Document the `draws_of` trick to emulate `rstan::extract()`

R/utils.R, tests/testthat/test-model-expose-functions.R
closes #947
Continue with compilation if `compile_stanalone=TRUE` but no functions are found. Changes mysterious Rcpp error to an informative warning. 
=> Warning but no error if `compile_standalone` but no functions found

.github/workflows/R-CMD-check-wsl.yaml, .github/workflows/R-CMD-check.yaml, .github/workflows/Test-coverage.yaml, .github/workflows/cmdstan-tarball-check.yaml, R/csv.R, R/utils.R, inst/include/base_rng.cpp, inst/include/model_methods.cpp, inst/include/rcpp_tuple_interop.hpp, inst/include/stan_rng.hpp, tests/testthat/test-model-compile.R, tests/testthat/test-model-expose-functions.R, tests/testthat/test-profiling.R
Test and fix issues with 2.35 RC
Andrew Johnson
=> Test and fix issues with 2.35 RC

R/utils.R, inst/include/stan_rng.hpp, tests/testthat/test-model-expose-functions.R
Exported RNG functions currently manage their state separately from R, so a user calling `set.seed()` has no effect on the result of the RNG.
This PR updates the exporting of RNG functions to additionally update their seed deterministically from the current seed in R
Andrew Johnson
=> Make exported RNG functions respect changes to R's seed

.gitignore, DESCRIPTION, R/utils.R, tests/testthat/test-model-expose-functions.R
Fix linking error when exposing SUNDIALS/KINSOL functions or model methods
Andrew Johnson
=> Fix linking error when exposing SUNDIALS/KINSOL functions or model methods

.github/workflows/R-CMD-check.yaml, R/install.R, R/model.R, R/utils.R, tests/testthat/test-install.R
Add CMDSTANR_USE_RTOOLS envvar to force use of stock RTools.
Closes #979 
Andrew Johnson
=> Add CMDSTANR_USE_RTOOLS envvar to force use of stock RTools

R/args.R
When using approximate inference algorithm fit objects as init there could be some errors that this PR fixes
- Issue: `lp__` or `lp_approx__` may contain NaN. NA, or Inf. Fix: replace non-finite `lw` with `-Inf`
- Issue: `pareto_smooth()` was estimating `r_eff`, but for independent draws from approximate normals `r_eff=1` should be used: Fix: add argument `r_eff=1` to `pareto_smooth()` call
=> fix process_init_approx

README.md, vignettes/cmdstanr.Rmd
Replace Stan package repo links with R-Universe
Andrew Johnson
=> Update repo links to use r-universe

.github/workflows/R-CMD-check.yaml, R/install.R, R/model.R, R/path.R, R/run.R, R/utils.R, tests/testthat/test-model-init.R
Collection of additional bugfixes
Andrew Johnson
=> Bugfixes - Fix Windows path change, aarch64 rtools, 2.35 seed changes

DESCRIPTION, NEWS.md
Prepare v0.8.1 bugfix release
Andrew Johnson
=> Prepare v0.8.1 bugfix release

R/model.R, R/utils.R
Compilation can fail for some systems when looking for include paths, as the quoting of arguments is handled differently when being passed to `make` as opposed to directly to `stanc`
Andrew Johnson
=> Fix compilation failures for Stan models with `#include` statements

R/utils.R
From [issue on the forums](https://discourse.mc-stan.org/t/tbb-interface-new-flag-is-not-working/35664/5): some flags in `make/local` (e.g., `TBB_INTERFACE_NEW`, etc.) weren't being passed to Rcpp when exposing functions and model methods  
Andrew Johnson
=> Include CmdStan CPPFLAGS when exposing functions

R/fit.R, man/fit-method-lp.Rd
The docs for 2.35 will have the change sampling statement -> distribution statement. This PR fixes the only mention in `cmdstanr` + uses new URL for the chapter
=> sampling statement -> distribution statement

R/model.R, man/model-method-format.Rd
Flagged in #1007, one of the code examples for the `format` method is for updating deprecated array syntax, which is not supported in CmdStan >= 2.34
Andrew Johnson
=> Remove unsupported array syntax formatting example

tests/testthat/test-fit-init.R
Fixes #976. As pointed out by @wpetry, the test for using pathfinder for inits when `psis_resample=FALSE` was missing the `psis_resample=FALSE`. 
=> Test pathfinder for initialization with psis_resample=FALSE

R/options.R, man/cmdstanr_global_options.Rd
`cmdstanr_print_line_numbers` was missing from the list of available global options
=> And `cmdstanr_print_line_numbers` to list of global options

R/fit.R
Improve computation of `r_eff` to better handle very small log-ratios.  See https://github.com/stan-dev/loo/issues/272. 
=> Improve stability of `r_eff` calculation for loo

R/fit.R, tests/testthat/test-fit-mcmc.R
closes #1032
Ensure there's an informative error message when calling `sampler_diagnostics()` when `fixed_param=TRUE`. 
=> Informative error message for sampler_diagnostics() with fixed_param

R/install.R
Fixes #1029
Uses @WardBrian [suggestion](https://github.com/stan-dev/cmdstanr/issues/1029#issuecomment-2476999046) of switching `untar`'s `exdir` to point to the parent directory, which would allow us to
> drop the --strip-components flag entirely, and then it wouldn't matter which tar implementation gets used, including internal. That way the testing/verifying the change is platform independent
- Documentation: CC-BY 4.0 …
=> Make use of untar() platform independent in `install_cmdstan()`

R/utils.R, tests/testthat/test-utils.R
- [ x] Run unit tests
- [ x] Declare copyright holder and agree to license (see below)
Fixes issue #1026 by allowing `repair_path()` to work with network paths. Updates the unit test accordingly.
(I filled in my name since that's part of the issue template)
Benjamin Schneider
```r
══ Results ═════════════════════════════════════════════════════════
Duration: 4639.4 s
── Skipped tests (13) …
```
=> For #1026: update `repair_path()` to work with network paths, add test.

tests/testthat/test-fit-init.R, tests/testthat/test-fit-laplace.R, tests/testthat/test-fit-shared.R, tests/testthat/test-model-compile.R, tests/testthat/test-model-expose-functions.R, tests/testthat/test-model-init.R, tests/testthat/test-model-laplace.R, tests/testthat/test-model-methods.R, tests/testthat/test-model-optimize.R, tests/testthat/test-model-pathfinder.R, tests/testthat/test-model-sample.R, tests/testthat/test-model-variables.R, tests/testthat/test-threads.R
Uses `utils::capture.output()` and other tricks in more places to reduce the amount of output printed to the console when running the unit tests. 
=> Reduce console output in tests 

R/csv.R, R/model.R, tests/testthat/test-model-sample.R
As of CmdStan 2.36 `fixed_param` is not required if the model has no parameters (e.g. only generated quantities). 
=> Don't require `fixed_param` for models with zero parameters (only GQs) for CmdStan >= 2.36

tests/testthat/test-failed-chains.R, tests/testthat/test-fit-mcmc.R
Following up on #1043, here are a few cases I missed. 
=> Suppress more output during tests to clean up logs

.github/workflows/R-CMD-check-wsl.yaml
The WSL CI has been hanging/timing-out for the last few runs, this PR updates the action to use WSL2 (only recently became available) which seems to fix the issue
Andrew Johnson
=> Update WSL CI to use WSL2

.github/workflows/R-CMD-check-wsl.yaml, .github/workflows/R-CMD-check.yaml, tests/testthat/test-opencl.R
This PR enables running the OpenCL tests in CI by using the POCL implementation CPU-based OpenCL. This also identified a handful of errors with the existing tests that I've fixed.
I haven't added Windows just yet, still have to see if there's a relatively simple way to include it.
Andrew Johnson
=> Enable OpenCL tests in CI for Linux, Mac, WSL

.github/workflows/R-CMD-check.yaml, DESCRIPTION, R/install.R, R/utils.R, man/fit-method-save_object.Rd, man/install_cmdstan.Rd, tests/testthat/test-install.R
From CmdStan 2.35 and RTools44 onwards we do not need to download/install any additional toolchains/utilities (e.g., `mingw32-make`). This PR updates our handling of toolchains to default to stock RTools (for rtools44 only), unless manually requested by the user setting the `CMDSTANR_USE_MSYS_TOOLCHAIN` environment variable.
Andrew Johnson
=> Use stock Rtools toolchain by default for RTools44+

R/fit.R
Should fix https://github.com/stan-dev/loo/issues/272. 
`$loo()` had the following line
```
r_eff <- loo::relative_eff(exp(LLarray + max(-LLarray)), cores = r_eff_cores)
```
It was possible to get `Inf` from exp, and the autocovariance function failed with input which was all `Inf`. There are two issued with this line, 1) it's using the maximum of whole -LLarray, but it would be better to translate each variable in LLarray with its own maximum, and 2) it's making the smallest value 0, while it should be the largest value which is 0. This PR fixes these two issues.
=> fix translation of log liks before exponentiation

DESCRIPTION, R/fit.R, R/model.R, cmdstanr.Rproj, man/CmdStanMLE.Rd, man/fit-method-loo.Rd, man/fit-method-mle.Rd, man/fit-method-save_object.Rd, man/model-method-optimize.Rd, tests/testthat/test-fit-mcmc.R
Closes #1051 
Closes #1052
* Fixes a mistake in the the loo method documentation (`variables` can actually only contain a single variable). 
* Adds some clarifying comments in the `optimize` and `CmdStanMLE` doc about the `jacobian` adjustment. 
=> Doc clarifications

tests/testthat/test-fit-gq.R, tests/testthat/test-fit-mcmc.R
The R-devel tests are currently failing with a `grepl` error:
```
Error in grepl(as.character(pattern), x, ignore.case, FALSE, perl, fixed,  : 
NA in coercion to boolean
```
It looks like this is caused by a couple of the `expect_match` calls accidentally including the input variable twice:
```r
expect_match(out[1], " variable", out[1])
```
The second `out[1]` is assumed to be a boolean argument and R tries to convert it. I think it's only started to error recently since they've been majorly reworking the handling of boolean types in R's C API (but that's just a guess)
Andrew Johnson …
=> Remove extra parameter breaking tests

R/install.R, R/utils.R, man/install_cmdstan.Rd
I had a look at the original [Math PR](https://github.com/stan-dev/math/pull/2999) adding compatibility with RTools `make`, and realised that it was compatible with all versions of RTools - not just RTools44!
This PR expands #1054 to use the stock Rtools toolchain for all cmdstan 2.35+ installations on Windows
Andrew Johnson
=> Expand default RTools toolchain usage to all R versions

DESCRIPTION, NEWS.md
Prepare items for v0.9.0 release
Andrew Johnson
=> Prepare items for v0.9.0 release

NEWS.md, README.md
This PR adds links to `Contributing` section at README.md to correctly reference the CONTRIBUTING.md and issues tab on GitHub.  
**Aalto University**
Aalto University
=> README.md update - References at Contributing section

R/model.R, R/path.R, tests/testthat/test-model-sample.R, tests/testthat/test-model-variables.R, tests/testthat/test-opencl.R
Precursor to #1022 .
To properly handle options when cmdstanr is provided a pre-compiled binary, we need to base arg checking on the cpp args and cmdstan version that the binary was complied with. This version may or may not be the same as the version currently set. This PR does not solve this problem completely. It is a precursor to the solution by at least storing **a** cmdstan version value in the model object.
Max Planck Institute of Animal Behavior
- …
=> Model specific version

tests/testthat/helper-mock-cli.R, tests/testthat/test-model-recompile-logic.R
Purpose is twofold:
- Add mocking infrastructure which allows us to test R code given particular outputs of cmdstan without actually running cmdstan
- Prep for improved cpp option handling (#1022 )
I ran the CI on my fork ([here](https://github.com/katrinabrock/cmdstanr/pull/4)). There are 3 failures, all of which I believe are unrelated to my change:
- macOS-latest (release) - issue in main, not sure root cause.
- windows-latest (release) - fix here: https://github.com/stan-dev/cmdstanr/pull/1076
- ubuntu-latest (release) - fix here: https://github.com/stan-dev/cmdstanr/pull/1077
Max Planck Institute of Animal Behavior
By submitting this pull request, the …
=> Add mock for stan cli

.github/workflows/R-CMD-check-wsl.yaml, .github/workflows/R-CMD-check.yaml
Cuts down on a bit of the CI churn/noise by using the default version of rtools for the given r-version, and using the higher-level actions version (e.g., `@v2` instead of `@v2.11.3`)
Andrew Johnson
=> Use default rtools & actions versions in CI

R/model.R
This logic will be reused in the initiate method for #1022  work. For now just breaking it into its own function.
Max Planck Institute of Animal Behavior
=> Extract exe path logic
